spring:
    datasource:
      password: 123
      url: jdbc:mysql://localhost:3306/study?userUnicode=true&characterEncoding=utf-8
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
      host: smtp.163.com
      username: erasernoobx@163.com
      password: STawXw5TmkzKxrNS

    data:
      redis:
        database: 0
        host: localhost
        port: 6379

